/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reloj;

import java.util.Calendar;
import java.util.Date;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;


/**
 *
 * @author jmcor
 */
public class AlarmaPanel extends javax.swing.JPanel {
    
    /**
     * Creates new form AlarmaPanel
     */
    public AlarmaPanel() {

//        SpinnerDateModel model = new SpinnerDateModel();
//        model.setCalendarField(Calendar.MINUTE);
//
//        jSpinnerAlarma.setModel(model);
//        jSpinnerAlarma.setEditor(new JSpinner.DateEditor(jSpinnerAlarma, "h:mm a"));

        initComponents();
    }

    public Alarma getSelectedValue() {
        
        Date date = (Date)jSpinnerAlarma.getValue();
        boolean activacion = jCheckBoxActivacion.isSelected();
        Alarma alarma = new Alarma(date, activacion);
        return alarma;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinnerAlarma = new javax.swing.JSpinner();
        jCheckBoxActivacion = new javax.swing.JCheckBox();

        jSpinnerAlarma.setModel(new javax.swing.SpinnerDateModel());

        jCheckBoxActivacion.setText("Activacion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSpinnerAlarma, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(jCheckBoxActivacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jCheckBoxActivacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinnerAlarma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBoxActivacion;
    private javax.swing.JSpinner jSpinnerAlarma;
    // End of variables declaration//GEN-END:variables
}
